In [4]:
from pandas_datareader import data
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
import yfinance as yf

#define the ticker symbol
tickerSymbol = 'MSFT'

#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

#get the historical prices for this ticker
tickerDf = tickerData.history(period='1d', start='2010-1-1', end='2020-04-14')

#see your data
tickerDf

              Open    High     Low   Close    Volume  Dividends  Stock Splits
Date
2009-12-31   24.32   24.33   23.93   23.93  31929700        0.0             0
2010-01-04   24.04   24.41   24.01   24.29  38409100        0.0             0
2010-01-05   24.22   24.41   24.05   24.30  49749600        0.0             0
2010-01-06   24.24   24.40   23.96   24.15  58182400        0.0             0
2010-01-07   24.04   24.10   23.70   23.90  50559700        0.0             0
...            ...     ...     ...     ...       ...        ...           ...
2020-04-06  160.32  166.50  157.58  165.27  67111700        0.0             0
2020-04-07  169.59  170.00  163.26  163.49  62769000        0.0             0
2020-04-08  165.67  166.67  163.50  165.13  48318200        0.0             0
2020-04-09  166.36  167.37  163.33  165.14  51431800        0.0             0
2020-04-13  164.35  165.57  162.30  165.51  41905300        0.0             0

[2587 rows x 7 columns]

In [17]:
#define the ticker symbol
tickerSymbol = 'MSFT'

#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

#get event data for ticker
tickerData.calendar

                                Value
Earnings Date     2020-04-29 00:00:00
Earnings Average                 1.29
Earnings Low                     1.17
Earnings High                    1.43
Revenue Average           34087700000
Revenue Low               32796000000
Revenue High              35111000000

In [9]:
#define the ticker symbol
tickerSymbol = 'MSFT'

#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

#get recommendation data for ticker
tickerData.recommendations

                      Firm       To Grade From Grade Action
Date
2012-03-16  Argus Research            Buy                up
2012-03-19  Hilliard Lyons  Long-Term Buy              main
2012-03-22  Morgan Stanley     Overweight              main
2012-04-03             UBS            Buy              main
2012-04-20   Goldman Sachs        Neutral              main
...                    ...            ...        ...    ...
2020-03-17   Deutsche Bank            Buy              main
2020-03-25  Morgan Stanley     Overweight              main
2020-03-31   Piper Sandler     Overweight              main
2020-03-31       Citigroup        Neutral              main
2020-04-03   Raymond James     Strong Buy              main

[271 rows x 4 columns]

In [10]:

#define the ticker symbol
tickerSymbol = 'MSFT'

#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

#info on the company
tickerData.info

{'zip': '98052',
 'sector': 'Technology',
 'fullTimeEmployees': 144000,
 'longBusinessSummary': "Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. The company's Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); and Skype, Outlook.com, and OneDrive. It also provides LinkedIn that includes Talent and marketing solutions, and subscriptions; and Dynamics 365, a set of cloud-based and on-premises business solutions for small and medium businesses, large organizations, and divisions of enterprises. Its Intelligent Cloud segment licenses SQL and Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also provides support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification to developers and IT professionals on various Microsoft products. The company's More Personal Computing segment offers Windows OEM licensing and other non-volume licensing of the Windows operating system; Windows Commercial comprising volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also provides Microsoft Surface, PC accessories, and other intelligent devices; Gaming, including Xbox hardware, and Xbox software and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through distributors and resellers; and directly through digital marketplaces, online stores, and retail stores. It has strategic partnerships with Humana Inc., Nokia, and Telkomsel. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'city': 'Redmond',
 'phone': '425-882-8080',
 'state': 'WA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.microsoft.com',
 'maxAge': 1,
 'address1': 'One Microsoft Way',
 'fax': '425-706-7329',
 'industry': 'Softwareâ€”Infrastructure',
 'previousClose': 173.7,
 'regularMarketOpen': 171.2,
 'twoHundredDayAverage': 155.85486,
 'trailingAnnualDividendYield': 0.011168682,
 'payoutRatio': 0.32930002,
 'volume24Hr': None,
 'regularMarketDayHigh': 171.55,
 'navPrice': None,
 'averageDailyVolume10Day': 54052016,
 'totalAssets': None,
 'regularMarketPreviousClose': 173.7,
 'fiftyDayAverage': 156.40172,
 'trailingAnnualDividendRate': 1.94,
 'open': 171.2,
 'toCurrency': None,
 'averageVolume10days': 54052016,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': 2.04,
 'exDividendDate': 1589932800,
 'beta': 0.962017,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 169.24,
 'priceHint': 2,
 'currency': 'USD',
 'trailingPE': 29.727415,
 'regularMarketVolume': 9423250,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 1298087280640,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 53723538,
 'priceToSalesTrailing12Months': 9.669251,
 'dayLow': 169.24,
 'ask': 170.22,
 'ytdReturn': None,
 'askSize': 1000,
 'volume': 9423250,
 'fiftyTwoWeekHigh': 190.7,
 'forwardPE': 27.571098,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 1.97,
 'fiftyTwoWeekLow': 119.01,
 'bid': 170.18,
 'tradeable': False,
 'dividendYield': 0.0123000005,
 'bidSize': 800,
 'dayHigh': 171.55,
 'exchange': 'NMS',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'messageBoardId': 'finmb_21835',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 9.026,
 'beta3Year': None,
 'profitMargins': 0.33016,
 'enterpriseToEbitda': 19.78,
 '52WeekChange': 0.4264598,
 'morningStarRiskRating': None,
 'forwardEps': 6.19,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 7606049792,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'bookValue': 14.467,
 'sharesShort': 58762671,
 'sharesPercentSharesOut': 0.0077,
 'fundFamily': None,
 'lastFiscalYearEnd': 1561852800,
 'heldPercentInstitutions': 0.74302,
 'netIncomeToCommon': 44323000320,
 'trailingEps': 5.741,
 'lastDividendValue': None,
 'SandP52WeekChange': -0.018752217,
 'priceToBook': 11.796855,
 'heldPercentInsiders': 0.01421,
 'nextFiscalYearEnd': 1625011200,
 'mostRecentQuarter': 1577750400,
 'shortRatio': 0.8,
 'sharesShortPreviousMonthDate': 1582848000,
 'floatShares': 7494998724,
 'enterpriseValue': 1211792883712,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1045526400,
 'lastSplitFactor': '2:1',
 'legalType': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.383,
 'dateShortInterest': 1585612800,
 'pegRatio': 2.19,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0077,
 'sharesShortPriorMonth': 37031775,
 'category': None,
 'fiveYearAverageReturn': None,
 'regularMarketPrice': 171.2,
 'logo_url': 'https://logo.clearbit.com/microsoft.com'}